using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._White.Contractors;


[GenerateTypedNameReferences]
public sealed partial class ContractsListEntry : BoxContainer
{
    public ContractsListEntry()
    {
        RobustXamlLoader.Load(this);
    }
}

