using System.Diagnostics.Contracts;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._White.Contractors;


[GenerateTypedNameReferences]
public sealed partial class ContractsList : FancyWindow
{
    public ContractsList()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddContract()
    {
        ContractsContainer.AddChild(new ContractsListEntry());
    }

    public void ReplacePlaceholder()
    {
        FirstTaskContainer.AddChild(new ContractsListEntry());
        FirstTaskPlaceholder.Visible = false;
    }
}


