using System.Diagnostics.Contracts;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._White.Contractors;


[GenerateTypedNameReferences]
public sealed partial class ContractsList : FancyWindow
{
    public ContractsList()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddContract(string name, string description, int telecrystalgGranted, float threatIncreased)
    {
        ContractsContainer.AddChild(new ContractsListEntry(name, description, telecrystalgGranted, threatIncreased));
    }
}


