using System.Globalization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._White.Contractors;


[GenerateTypedNameReferences]
public sealed partial class ContractsListEntry : BoxContainer
{
    public ContractsListEntry(string name, string description, int telecrystalGranted, float threatIncreased)
    {
        RobustXamlLoader.Load(this);
        NameLabel.Text = name;
        DescriptionLabel.Text = description;
        TelecrystalLabel.Text = "Telecrystals granted: " + telecrystalGranted.ToString();
        ThreatLabel.Text = "Reputation granted: " + threatIncreased.ToString();
    }
}

